### ISSUE TITLE
jQuery 2.0.0 support

### ISSUE THREAD

**Issue by zianwar** [jweisbeck/Crossword#6]
Hi, is there a way to get this working for jQuery 2.0.0 ? 

I get this error : 

```
Uncaught Error: Syntax error, unrecognized expression: [object Object][data-coords="2,1"]
```

**Comment by HoldOffHunger** [comment]
I'm not sure if this helps, but I've coded up a crossword puzzle generator and game that uses the jQuery v. 3.2.1.  BSD licensed: https://github.com/HoldOffHunger/jquery-crossword-puzzle-generator

You can see an online demo if it here: http://www.earthfluent.com/crossword-puzzle-demo.html
